name: Lint

on: push

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install --global prettier

      - name: Lint
        run: prettier --check .
